/*******************************************************************************
* File Name: cycfg_capsense.h
* Version: 3.0
*
* Description:
* CapSense Middleware configuration
* This file should not be modified. It was automatically generated by
* CapSense Configurator 3.0.0.2188
*
********************************************************************************
* Copyright 2020 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_CAPSENSE_H)
#define CYCFG_CAPSENSE_H

#include <stddef.h>
#include "cy_device_headers.h"
#include "cycfg_peripherals.h"

#define CY_CAPSENSE_CFG_TOOL_VERSION              (300)

#if !defined(CY_DISABLE_CAPSENSE)

#if (CY_CAPSENSE_CORE == __CORTEX_M)


#if !defined(CY_CAPSENSE_CPU_CLK)
#error CPU clock frequency is not set: missing #define CY_CAPSENSE_CPU_CLK
#endif

#if !defined(CY_CAPSENSE_PERI_CLK)
#error Peripheral clock core is not set: missing #define CY_CAPSENSE_PERI_CLK
#endif

#if !defined(CY_CAPSENSE_VDDA_MV)
#error VDDA voltage is not set: missing #define CY_CAPSENSE_VDDA_MV
#endif

#if !defined(CY_CAPSENSE_PERI_DIV_TYPE)
#error Peripheral clock divider type is not set: missing #define CY_CAPSENSE_PERI_DIV_TYPE
#endif

#if !defined(CY_CAPSENSE_PERI_DIV_INDEX)
#error Peripheral clock divider index is not set: missing #define CY_CAPSENSE_PERI_DIV_INDEX
#endif



#include "cy_capsense.h"

/* Supported CapSense Middleware version */
#define CY_CAPSENSE_MW_VERSION_REQUIRED           (200)

#if !defined (CY_CAPSENSE_MW_VERSION)
    #if (CY_CAPSENSE_MW_VERSION_MAJOR == 2)
        #define CY_CAPSENSE_MW_VERSION            (200)
    #elif (CY_CAPSENSE_MW_VERSION_MAJOR == 1)
        #define CY_CAPSENSE_MW_VERSION            (100)
    #else
        #define CY_CAPSENSE_MW_VERSION            (100)
    #endif
#endif

/* Check the used Middleware version */
#if (CY_CAPSENSE_MW_VERSION_REQUIRED > CY_CAPSENSE_MW_VERSION)
    #error The CapSense Configurator requires a newer version of the CapSense Middleware. Update the CapSense Middleware in your project.
#endif

#define CY_CAPSENSE_BIST_SUPPORTED                (CY_CAPSENSE_MW_VERSION >= 210)

#if defined(__cplusplus)
extern "C" {
#endif

/*Widget names */

/* Sensing Methods */
#define CY_CAPSENSE_CSD_EN                                                       (0u)
#define CY_CAPSENSE_CSX_EN                                                       (0u)
#define CY_CAPSENSE_CSD_CALIBRATION_EN                                           (0u)
#define CY_CAPSENSE_CSX_CALIBRATION_EN                                           (0u)
#define CY_CAPSENSE_SMARTSENSE_FULL_EN                                           (0u)
#define CY_CAPSENSE_SMARTSENSE_HW_EN                                             (0u)
#define CY_CAPSENSE_SMARTSENSE_DISABLED                                          (1u)
#define CY_CAPSENSE_CSD_SHIELD_EN                                                (0u)
#define CY_CAPSENSE_CSD_SHIELD_CAP_EN                                            (0u)

/* Filtering */
#define CY_CAPSENSE_ADAPTIVE_FILTER_EN                                           (0u)
#define CY_CAPSENSE_BALLISTIC_MULTIPLIER_EN                                      (0u)
#define CY_CAPSENSE_RAWCOUNT_FILTER_EN                                           (0u)
#define CY_CAPSENSE_POSITION_FILTER_EN                                           (0u)
#define CY_CAPSENSE_CSD_POSITION_FILTER_EN                                       (0u)
#define CY_CAPSENSE_CSX_POSITION_FILTER_EN                                       (0u)

/* Widgets */
#define CY_CAPSENSE_CSD_BUTTON_EN                                                (0u)
#define CY_CAPSENSE_CSD_MATRIX_EN                                                (0u)
#define CY_CAPSENSE_CSD_SLIDER_EN                                                (0u)
#define CY_CAPSENSE_CSD_TOUCHPAD_EN                                              (0u)
#define CY_CAPSENSE_CSD_PROXIMITY_EN                                             (0u)
#define CY_CAPSENSE_CSX_BUTTON_EN                                                (0u)
#define CY_CAPSENSE_CSX_MATRIX_EN                                                (0u)
#define CY_CAPSENSE_CSX_TOUCHPAD_EN                                              (0u)
#define CY_CAPSENSE_ADVANCED_CENTROID_5X5_EN                                     (0u)
#define CY_CAPSENSE_CSD_LINEAR_SLIDER_EN                                         (0u)
#define CY_CAPSENSE_CSD_RADIAL_SLIDER_EN                                         (0u)
#define CY_CAPSENSE_CSD_DIPLEX_SLIDER_EN                                         (0u)

/* Features */
#define CY_CAPSENSE_GESTURE_EN                                                   (0u)
#define CY_CAPSENSE_MULTI_FREQUENCY_SCAN_EN                                      (0u)
#define CY_CAPSENSE_SNS_AUTO_RESET_EN                                            (0u)
#define CY_CAPSENSE_BIST_EN                                                      (0u)


typedef struct {
    cy_stc_capsense_common_context_t commonContext;
    cy_stc_capsense_widget_context_t widgetContext[0];
    cy_stc_capsense_sensor_context_t sensorContext[0];
} cy_stc_capsense_tuner_t;

extern cy_stc_capsense_tuner_t cy_capsense_tuner;

extern cy_stc_capsense_context_t cy_capsense_context;

/* RAM Data structure register definitions */
#define CY_CAPSENSE_CONFIG_ID_VALUE                                              (cy_capsense_tuner.commonContext.configId)
#define CY_CAPSENSE_CONFIG_ID_OFFSET                                             (0u)
#define CY_CAPSENSE_CONFIG_ID_SIZE                                               (2u)
#define CY_CAPSENSE_CONFIG_ID_PARAM_ID                                           (0x02000000u)

#define CY_CAPSENSE_TUNER_CMD_VALUE                                              (cy_capsense_tuner.commonContext.tunerCmd)
#define CY_CAPSENSE_TUNER_CMD_OFFSET                                             (2u)
#define CY_CAPSENSE_TUNER_CMD_SIZE                                               (2u)
#define CY_CAPSENSE_TUNER_CMD_PARAM_ID                                           (0x02000002u)

#define CY_CAPSENSE_SCAN_COUNTER_VALUE                                           (cy_capsense_tuner.commonContext.scanCounter)
#define CY_CAPSENSE_SCAN_COUNTER_OFFSET                                          (4u)
#define CY_CAPSENSE_SCAN_COUNTER_SIZE                                            (2u)
#define CY_CAPSENSE_SCAN_COUNTER_PARAM_ID                                        (0x02000004u)

#define CY_CAPSENSE_TUNER_ST_VALUE                                               (cy_capsense_tuner.commonContext.tunerSt)
#define CY_CAPSENSE_TUNER_ST_OFFSET                                              (6u)
#define CY_CAPSENSE_TUNER_ST_SIZE                                                (1u)
#define CY_CAPSENSE_TUNER_ST_PARAM_ID                                            (0x01000006u)

#define CY_CAPSENSE_INITDONE_VALUE                                               (cy_capsense_tuner.commonContext.initDone)
#define CY_CAPSENSE_INITDONE_OFFSET                                              (7u)
#define CY_CAPSENSE_INITDONE_SIZE                                                (1u)
#define CY_CAPSENSE_INITDONE_PARAM_ID                                            (0x01000007u)

#define CY_CAPSENSE_PTRSSCALLBACK_VALUE                                          (cy_capsense_tuner.commonContext.ptrSSCallback)
#define CY_CAPSENSE_PTRSSCALLBACK_OFFSET                                         (8u)
#define CY_CAPSENSE_PTRSSCALLBACK_SIZE                                           (4u)
#define CY_CAPSENSE_PTRSSCALLBACK_PARAM_ID                                       (0x03000008u)

#define CY_CAPSENSE_PTREOSCALLBACK_VALUE                                         (cy_capsense_tuner.commonContext.ptrEOSCallback)
#define CY_CAPSENSE_PTREOSCALLBACK_OFFSET                                        (12u)
#define CY_CAPSENSE_PTREOSCALLBACK_SIZE                                          (4u)
#define CY_CAPSENSE_PTREOSCALLBACK_PARAM_ID                                      (0x0300000cu)

#define CY_CAPSENSE_PTRTUNERSENDCALLBACK_VALUE                                   (cy_capsense_tuner.commonContext.ptrTunerSendCallback)
#define CY_CAPSENSE_PTRTUNERSENDCALLBACK_OFFSET                                  (16u)
#define CY_CAPSENSE_PTRTUNERSENDCALLBACK_SIZE                                    (4u)
#define CY_CAPSENSE_PTRTUNERSENDCALLBACK_PARAM_ID                                (0x03000010u)

#define CY_CAPSENSE_PTRTUNERRECEIVECALLBACK_VALUE                                (cy_capsense_tuner.commonContext.ptrTunerReceiveCallback)
#define CY_CAPSENSE_PTRTUNERRECEIVECALLBACK_OFFSET                               (20u)
#define CY_CAPSENSE_PTRTUNERRECEIVECALLBACK_SIZE                                 (4u)
#define CY_CAPSENSE_PTRTUNERRECEIVECALLBACK_PARAM_ID                             (0x03000014u)

#define CY_CAPSENSE_STATUS_VALUE                                                 (cy_capsense_tuner.commonContext.status)
#define CY_CAPSENSE_STATUS_OFFSET                                                (24u)
#define CY_CAPSENSE_STATUS_SIZE                                                  (4u)
#define CY_CAPSENSE_STATUS_PARAM_ID                                              (0x03000018u)

#define CY_CAPSENSE_TIMESTAMPINTERVAL_VALUE                                      (cy_capsense_tuner.commonContext.timestampInterval)
#define CY_CAPSENSE_TIMESTAMPINTERVAL_OFFSET                                     (28u)
#define CY_CAPSENSE_TIMESTAMPINTERVAL_SIZE                                       (4u)
#define CY_CAPSENSE_TIMESTAMPINTERVAL_PARAM_ID                                   (0x0300001cu)

#define CY_CAPSENSE_TIMESTAMP_VALUE                                              (cy_capsense_tuner.commonContext.timestamp)
#define CY_CAPSENSE_TIMESTAMP_OFFSET                                             (32u)
#define CY_CAPSENSE_TIMESTAMP_SIZE                                               (4u)
#define CY_CAPSENSE_TIMESTAMP_PARAM_ID                                           (0x03000020u)

#define CY_CAPSENSE_CSD_MOD_CLK_DIVIDER_VALUE                                    (cy_capsense_tuner.commonContext.modCsdClk)
#define CY_CAPSENSE_CSD_MOD_CLK_DIVIDER_OFFSET                                   (36u)
#define CY_CAPSENSE_CSD_MOD_CLK_DIVIDER_SIZE                                     (1u)
#define CY_CAPSENSE_CSD_MOD_CLK_DIVIDER_PARAM_ID                                 (0x01000024u)

#define CY_CAPSENSE_CSX_MOD_CLK_DIVIDER_VALUE                                    (cy_capsense_tuner.commonContext.modCsxClk)
#define CY_CAPSENSE_CSX_MOD_CLK_DIVIDER_OFFSET                                   (37u)
#define CY_CAPSENSE_CSX_MOD_CLK_DIVIDER_SIZE                                     (1u)
#define CY_CAPSENSE_CSX_MOD_CLK_DIVIDER_PARAM_ID                                 (0x01000025u)

#define CY_CAPSENSE_TUNER_CNT_VALUE                                              (cy_capsense_tuner.commonContext.tunerCnt)
#define CY_CAPSENSE_TUNER_CNT_OFFSET                                             (38u)
#define CY_CAPSENSE_TUNER_CNT_SIZE                                               (1u)
#define CY_CAPSENSE_TUNER_CNT_PARAM_ID                                           (0x01000026u)




#if (CY_CAPSENSE_BIST_SUPPORTED)
#if (CY_CAPSENSE_BIST_EN != 0)
extern uint32_t eltdCap[];

extern uint16_t bslnInv[];
#endif
#endif

#if defined(__cplusplus)
}
#endif

#endif /* CY_CAPSENSE_CORE == __CORTEX_M */

#endif /* !defined(CY_DISABLE_CAPSENSE) */

#endif /* CYCFG_CAPSENSE_H */

/* [] END OF FILE */

